service:
  - docker

notifications:
  email: false

git:
  depth: false
  quiet: true

language: java
jdk: oraclejdk8
node_js: lts/*

addons:
  apt:
    packages:
      - sudo
      - lsof
      - curl
      - bash
      - docker-ce
      - python-pip
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable

install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #
  - sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5432 8443 9990 9999

script:
#  - ./mvnw -pl :backend,:frontend >/dev/null
#  - ./mvnw -pl :backend >/dev/null
#  - ./mvnw -f docker/pom.xml -P ci-up
#  - ./bin/tail-logs.sh &
#  - http    get 0.0.0.0:8080/blog
#  - http    get 0.0.0.0:8080/blog/
#  - http    get 0.0.0.0:8080/blog/index.html
#  - http    get 0.0.0.0:8080/blog/api
#  - http    get 0.0.0.0:8080/blog/api/v1/posts/find-by-id id=00000000-0000-0000-0000-000000000000            || echo 'expected 400 HTTP status code.'
#  - http   post 0.0.0.0:8080/blog/api/v1/posts/create data="# trololo"
#  - http    get 0.0.0.0:8080/blog/api/v1/posts/find-all
#  - http    put 0.0.0.0:8080/blog/api/v1/posts/update id=00000000-0000-0000-0000-000000000000 data="# ololo" || echo 'expected 400 HTTP status code.'
#  - http delete 0.0.0.0:8080/blog/api/v1/posts/delete id=00000000-0000-0000-0000-000000000000                || echo 'expected 400 HTTP status code.'
#  - ./mvnw -pl :docker -Pci-down

  - ./mvnw -pl :backend,:frontend >/dev/null
  - ./mvnw -f docker/pom.xml -P ci-up
  - ./mvnw -f integration-tests/pom.xml -P ci

cache:
  directories:
    - ./frontend/node_modules
    - ~/.docker
    - ~/.m2
