service:
  - docker

notifications:
  email: false

git:
  depth: false
  quiet: true

language: java
jdk: oraclejdk8
node_js: lts/*

addons:
  apt:
    packages:
      - sudo
      - lsof
      - curl
      - bash
      - docker-ce
      - python-pip
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable

install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #
  - sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 5432

script:
  - ./mvnw -pl :backend,:frontend
  - ./mvnw -pl :docker -Pdocker docker-compose:up
  #- docker-compose -f ./docker/src/main/docker/docker-compose.yaml logs -f -t &
  - while [[ $(docker ps --quiet --last 2 --filter health=healthy | wc -l) -lt 2 ]] ; do
      echo -ne '.' ; sleep 2s ;
    done
  - http posts :8080/blog/api/
  - http posts :8080/blog/api/posts/new?postText=trololo
  - http posts :8080/blog/api/posts/all
  - http posts :8080/blog/api/posts/one id=00000000-0000-0000-0000-000000000000                 || echo 'expected 400 HTTP status code.'
  - http put :8080/blog/api/posts/edit id=00000000-0000-0000-0000-000000000000 postText=ololo  || echo 'expected 400 HTTP status code.'
