version: '2.1'
services:
  postgres:
    image: healthcheck/postgres:alpine
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    networks:
      my-blog.com:
        aliases:
          - db.my-blog.com
  jboss:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_HOST: db.my-blog.com
    networks:
      my-blog.com:
        aliases:
          - blog.my-blog.com
          - jboss.my-blog.com
networks:
  my-blog.com:
    driver: bridge