
== REST API documentation

=== Show API description
[cols="30%,70%"]
|===
|*Title* |*Show API description*

Returns json data with API description.

|*URL*
| `/api`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|None

|*Success Response*
|*Code:* 200 OK

*Content:* ``{
               "links": {
                   "_self              ": "http://localhost:8080/blog/api",
                   "create post:       ": "http://localhost:8080/blog/api/v1/posts/create  title={markdown} body={markdown}",
                   "find all posts     ": "http://localhost:8080/blog/api/v1/posts/find-all",
                   "find post by id    ": "http://localhost:8080/blog/api/v1/posts/find-by-id id={uuid}",
                   "health status      ": "http://localhost:8080/blog/api/health",
                   "update posts:      ": "http://localhost:8080/blog/api/v1/posts/update id={uuid}"
                   "remove posts:      ": "http://localhost:8080/blog/api/v1/posts/delete id={uuid} title={markdown} body={markdown}"
               }
           } ``
|===
=== Create new post
[cols="30%,70%"]
|===
|*Title* |*Create new post*

Returns location of created post.

|*URL*
| `/api/v1/posts/create`

|*Method*
|`POST`

|*URL Params*
|*Required:*

|None
|*Data Params*

`title=[String]  body=[String]`

|*Success Response*
|*Code:* 201 Created

*Content:* ``{} ``

*Location:* `/blogapiv1postscreateid=:id`
|===

=== Show all posts
[cols="30%,70%"]
|===
|*Title* |*Show all posts*

Returns json data of all posts.


|*URL*
| `/api/v1/posts/find-all`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|None
|*Success Response*
|*Code:* 200 OK

*Content:*
[
    {
        "body": "ololo",
        "id": "674b289d-1f3f-4285-beef-79e27772b3e6",
        "lastModifiedAt": "2019.02.15 15:30 GMT",
        "title": "title"
    }
]
|===
=== Show one post
[cols="30%,70%"]
|===
|*Title* |*Show one post*

Returns json data of one post.

|*URL*
| `/api/v1/posts/find-by-id`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|`id=[UUID]`
|*Success Response*
|*Code:* 200 OK

*Content:* ``
{
    "body": "ololo",
    "id": "674b289d-1f3f-4285-beef-79e27772b3e6",
    "lastModifiedAt": "2019.02.15 15:30 GMT",
    "title": "title"
}
 ``
|===
=== Edit post
[cols="30%,70%"]
|===
|*Title* |*Show one edited post*

Returns json data of one edited post.

|*URL*
| `/api/v1/posts/update`

|*Method*
|`PUT`

|*URL Params*
|*Required:*

None
|*Data Params*
|`id=[UUID]`

`title=[String] body=[String]`
|*Success Response*
|*Code:* 200 OK

*Content:* ``
{
    "body": "trololo",
    "id": "674b289d-1f3f-4285-beef-79e27772b3e6",
    "lastModifiedAt": "2019.02.15 15:58 GMT",
    "title": "title"
}
 ``
|===
=== Delete post
[cols="30%,70%"]
|===
|*Title* |*Show one post*

Returns json data of one post.

|*URL*
| `/api/v1/posts/delete`

|*Method*
|`DELETE`

|*URL Params*
|*Required:*

None
|*Data Params*
|`id=[UUID]`
|*Success Response*
|*Code:* 200 OK

*Content:* ``
{
    "message": "Post with id '674b289d-1f3f-4285-beef-79e27772b3e6' was removed."
}
 ``
|===