
== REST API documentation

=== Show API description
[cols="30%,70%"]
|===
|*Title* |*Show API description*

Returns json data with API description.

|*URL*
| `/api`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|None

|*Success Response*
|*Code:* 200 OK

*Content:* ``{
               "links": {
                   "_self           GET": "http://localhost:8080/blog/api",
                   "create post:       POST": "http://localhost:8080/blog/api/v1/posts/create",
                   "find all posts     GET": "http://localhost:8080/blog/api/v1/posts/find-all",
                   "find post by id    GET": "http://localhost:8080/blog/api/v1/posts/find-by-id",
                   "health status      GET": "http://localhost:8080/blog/api/health",
                   "update posts:      PUT": "http://localhost:8080/blog/api/v1/posts/update"
                   "remove posts:      PUT": "http://localhost:8080/blog/api/v1/posts/delete"
               }
           } ``
|===
=== Create new post
[cols="30%,70%"]
|===
|*Title* |*Create new post*

Returns location of created post.

|*URL*
| `/api/post/new`

|*Method*
|`POST`

|*URL Params*
|*Required:*

`data=[String]`
|*Data Params*
|None

|*Success Response*
|*Code:* 201 Created

*Content:* ``{} ``

*Location:* `/blog/api/post/new/api/post/new?id=:id`
|===

=== Show all posts
[cols="30%,70%"]
|===
|*Title* |*Show all posts*

Returns json data of all posts.


|*URL*
| `/api/post/all`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|None
|*Success Response*
|*Code:* 200 OK

*Content:* ``{"post":
[
{"body":"trololo","id":"9b4366bd-e0e6-4c0b-b46a-4329efadd5a1","when":"2019.01.18 15:57 GMT"},{"body":"ololo","id":"d9252cb6-88e8-4a92-831e-745241ffe3f7","when":"2019.01.18 15:00 GMT"}]} ``

|===
=== Show one post
[cols="30%,70%"]
|===
|*Title* |*Show one post*

Returns json data of one post.


|*URL*
| `/api/post/one`

|*Method*
|`GET/POST`

|*URL Params*
|*Required:*

None
|*Data Params*
|`id=[UUID]`
|*Success Response*
|*Code:* 200 OK

*Content:* ``
{
    "postResponse": {
        "body": "trololo",
        "id": "5e48ee43-d428-4bbe-bcbc-0d860ca96e63",
        "when": "2019.01.18 13:25 GMT"
    }
}
 ``
|===
=== Edit one post
[cols="30%,70%"]
|===
|*Title* |*Show one edited post*

Returns json data of one edited post.

|*URL*
| `/api/post/edit`

|*Method*
|`PUT`

|*URL Params*
|*Required:*

None
|*Data Params*
|`id=[UUID]`

`data=[String]`
|*Success Response*
|*Code:* 200 OK

*Content:* ``
{
    "postResponse": {
        "body": "editedOlolo",
        "id": "4e103103-9d5a-42ec-873a-58f1bed6ef44",
        "when": "2019.01.18 13:27 GMT"
    }
}
 ``
|===
